services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    networks:
      - coolify
    environment:
      - HOST=0.0.0.0
      - OLLAMA_BASE_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    restart: unless-stopped
    volumes:
      - openwebui_data:/app/backend/data

networks:
  coolify:
    external: true

volumes:
  openwebui_data:
