services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    networks:
      - coolify
    ports:
      - "10101:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwebui.rule=Host(`ai.gruenstifter.com`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
    restart: unless-stopped
    volumes:
      - openwebui_data:/app/backend/data

networks:
  coolify:
    external: true

volumes:
  openwebui_data:
