version: '3.9'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwebui.rule=Host(`ai.gruenstifter.com`)
      - traefik.http.services.openwebui.loadbalancer.server.port=8080
      - traefik.http.routers.openwebui.entrypoints=websecure
      - traefik.http.routers.openwebui.tls.certresolver=letsencrypt
      - traefik.http.routers.openwebui.middlewares=https-redirect@file
      - coolify.managed=true  # Required for Coolify integration
      - coolify.network=coolify
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - coolify  # Correct network name

networks:
  coolify:  # Matches Coolify's network
    external: true

volumes:
  openwebui_data:
